[package]
name = "niri"
version = "0.1.0"
description = "A scrollable-tiling Wayland compositor"
authors = ["Ivan Molodetskikh <yalterz@gmail.com>"]
license = "GPL-3.0-or-later"
edition = "2021"

[dependencies]
anyhow = { version = "1.0.72", features = ["backtrace"] }
bitflags = "2.3.3"
clap = { version = "4.3.21", features = ["derive"] }
keyframe = { version = "1.1.1", default-features = false }
profiling = "1.0.9"
smithay-drm-extras = { version = "0.1.0", path = "../smithay/smithay-drm-extras" }
tracing = "0.1.37"
tracing-subscriber = { version = "0.3.17", features = ["env-filter"] }
tracy-client = { version = "0.15.2", default-features = false }
xcursor = "0.3.4"

[dependencies.smithay]
git = "https://github.com/Smithay/smithay"
default-features = false
features = [
    "backend_drm",
    "backend_egl",
    "backend_gbm",
    "backend_libinput",
    "backend_session_libseat",
    "backend_udev",
    "backend_winit",
    "desktop",
    "renderer_gl",
    "renderer_multi",
    "use_system_lib",
    "wayland_frontend",
]

[features]
profile-with-tracy = ["profiling/profile-with-tracy", "tracy-client/default"]

[profile.release]
overflow-checks = true
