[package]
name = "niri"
version = "0.1.0"
description = "A scrollable-tiling Wayland compositor"
authors = ["Ivan Molodetskikh <yalterz@gmail.com>"]
license = "GPL-3.0-or-later"
edition = "2021"

[dependencies]
anyhow = { version = "1.0.72" }
bitflags = "2.3.3"
clap = { version = "4.3.21", features = ["derive"] }
directories = "5.0.1"
image = { version = "0.24.7", default-features = false, features = ["png"] }
keyframe = { version = "1.1.1", default-features = false }
logind-zbus = "3.1.2"
profiling = "1.0.9"
sd-notify = "0.4.1"
time = { version = "0.3.28", features = ["formatting", "local-offset", "macros"] }
tracing = { version = "0.1.37", features = ["max_level_trace", "release_max_level_debug"] }
tracing-subscriber = { version = "0.3.17", features = ["env-filter"] }
tracy-client = { version = "0.15.2", default-features = false }
xcursor = "0.3.4"
zbus = { version = "3.14.1" }

[dependencies.smithay]
git = "https://github.com/Smithay/smithay.git"
default-features = false
features = [
    "backend_drm",
    "backend_egl",
    "backend_gbm",
    "backend_libinput",
    "backend_session_libseat",
    "backend_udev",
    "backend_winit",
    "desktop",
    "libinput_1_19",
    "renderer_gl",
    "renderer_multi",
    "use_system_lib",
    "wayland_frontend",
]

[dependencies.smithay-drm-extras]
git = "https://github.com/Smithay/smithay.git"

[features]
profile-with-tracy = ["profiling/profile-with-tracy", "tracy-client/default"]

[profile.release]
overflow-checks = true

[package.metadata.generate-rpm]
assets = [
    { source = "target/release/niri", dest = "/usr/bin/", mode = "755" },
    { source = "resources/niri-session", dest = "/usr/bin/", mode = "755" },
    { source = "resources/niri.desktop", dest = "/usr/share/wayland-sessions/", mode = "644" },
    { source = "resources/niri.service", dest = "/usr/lib/systemd/user/", mode = "644" },
]
[package.metadata.generate-rpm.requires]
alacritty = "*"
fuzzel = "*"
